CREATE USER 'larele'@'127.0.0.1' IDENTIFIED BY 'a1ad82a06fb30a71f9470fedfe811243dd5c8c8c';

GRANT SELECT, INSERT, UPDATE, DELETE, CREATE, DROP, REFERENCES, INDEX, ALTER, LOCK TABLES, EXECUTE, CREATE VIEW, SHOW VIEW ON *.* TO 'larele'@'127.0.0.1';

GRANT SELECT, INSERT, UPDATE, REFERENCES, DELETE, CREATE, DROP, ALTER, INDEX, TRIGGER, CREATE VIEW, SHOW VIEW, EXECUTE, ALTER ROUTINE, CREATE ROUTINE, CREATE TEMPORARY TABLES, LOCK TABLES, EVENT ON `larele`.* TO 'larele'@'127.0.0.1';

GRANT GRANT OPTION ON `larele`.* TO 'larele'@'127.0.0.1';
